# Generated by Django 4.0.6 on 2022-11-12 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_section',
            name='tags',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
