# Generated by Django 4.0.6 on 2022-11-12 15:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0002_pre_section_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple_section',
            name='ck_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='simple_section',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
