# Generated by Django 4.0.6 on 2022-11-12 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0003_simple_section_ck_text_alter_simple_section_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('th', models.CharField(max_length=100)),
                ('td', models.CharField(max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sections', to='mein.themes')),
            ],
        ),
    ]
