# Generated by Django 4.0.6 on 2022-11-12 16:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0004_table_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_section',
            name='td',
        ),
        migrations.RemoveField(
            model_name='table_section',
            name='th',
        ),
        migrations.CreateModel(
            name='Tr_td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_td', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_td', to='mein.table_section')),
            ],
        ),
    ]
