# Generated by Django 4.0.6 on 2022-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0006_table_section_th'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_section',
            name='td',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table_section',
            name='th',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tr_td',
        ),
    ]
