# Generated by Django 4.0.6 on 2022-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0007_table_section_td_alter_table_section_th_delete_tr_td'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=200)),
            ],
        ),
    ]
