# Generated by Django 4.0.6 on 2022-11-15 09:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0008_foobar'),
    ]

    operations = [
        migrations.AddField(
            model_name='foobar',
            name='post_nominals',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, null=True, size=6),
        ),
    ]
