# Generated by Django 4.0.6 on 2022-11-15 09:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0009_foobar_post_nominals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foobar',
        ),
        migrations.AlterField(
            model_name='table_section',
            name='td',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=100, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='table_section',
            name='th',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=100, null=True, size=None),
        ),
    ]
