# Generated by Django 4.0.6 on 2022-11-15 09:46

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0010_delete_foobar_alter_table_section_td_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_section',
            name='td',
        ),
        migrations.CreateModel(
            name='Tr_td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=100, null=True, size=None)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_td', to='mein.table_section')),
            ],
        ),
    ]
