# Generated by Django 4.0.6 on 2022-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0011_remove_table_section_td_tr_td'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pre_section',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simple_section',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simple_section',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
