# Generated by Django 4.0.6 on 2022-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0012_department_link_alter_pre_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='link',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
