# Generated by Django 4.0.6 on 2022-11-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0013_themes_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='link',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='link',
        ),
    ]
