# Generated by Django 4.0.5 on 2022-11-25 10:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0014_remove_department_link_remove_themes_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_section',
            name='th',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=100, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tr_td',
            name='td',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=100, null=True, size=None),
        ),
    ]
